name: landing_page_zupt
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  http: ^1.2.1
  google_fonts: ^6.1.0
  validatorless: ^1.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/fonts/
  fonts:
    - family: Comfortaa
      fonts:
        - asset: assets/fonts/Comfortaa/Comfortaa-Bold.ttf
          weight: 700
        - asset: assets/fonts/Comfortaa/Comfortaa-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Comfortaa/Comfortaa-Medium.ttf
          weight: 500
        - asset: assets/fonts/Comfortaa/Comfortaa-Regular.ttf
          weight: 400
        - asset: assets/fonts/Comfortaa/Comfortaa-Light.ttf
          weight: 300